### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by liwell24** [gzaraunitn/autolabel#2]
Thank you for the great work of open source！
Could you tell me where to download the dataset ？
Looking forward to your reply~

**Comment by gzaraunitn** [comment]
Hi, thanks for your issue. The [HMDB](https://serre-lab.clps.brown.edu/resource/hmdb-a-large-human-motion-database/#Downloads) and [UCF](https://www.crcv.ucf.edu/data/UCF101.php) datasets are both available for download. You can refer to the [TA3N](https://arxiv.org/pdf/1907.12743.pdf) work (page 11) for the 12 classes that overlap between the two datasets and their naming, and to [CEVT](https://arxiv.org/pdf/2109.00522.pdf) for the chosen open-set split. As for Epic-Kitchens, you can use the official [download scripts](https://github.com/epic-kitchens/epic-kitchens-download-scripts): you should download the frames (`--frames`) for kitchens P01, P08 and P22. Best!

**Comment by liwell24** [comment]
Thank u for your reply！
I met some problem when i reproduce OUVDA on epic-kitchens, the error message as follows

```
_K-means: loading training set
  0%|          | 0/234 [00:00<?, ?it/s]
Error executing job with overrides: ['setting=ek12', 'attributes.n_attributes=6', 'attributes.tf_idf_threshold=0.5', 'attributes.matching_threshold=0.5', 'attributes.selection=topk', 'attributes.k_clustering=45', 'attributes.tf_idf_topk_source=5', 'attributes.tf_idf_topk_target=5', 'attributes.final_prompt_length=3', 'loss.target.weight=1.0', 'loss.target.filtering=top_k_confident_samples', 'loss.target.k=20', 'loss.target.k_type=percentage', 'data.batch_size=16', 'solver.type=cosine', 'solver.epochs=20', 'solver.lr=6.e-6', 'logging.comet=True', 'logging.tag=ek12', 'logging.project_name=autolabel']
Traceback (most recent call last):
  File "../train.py", line 218, in main
    training_results = training_step(
  File "/home/lw/autolabel-main/loops/training_step.py", line 71, in training_step
    clustering_results = clustering_method(model, loader["target"], config, device)
  File "/home/lw/autolabel-main/utils/attributes.py", line 34, in k_means
    for batch_idx, (
  File "/home/lw/anaconda3/envs/autolabel/lib/python3.8/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/home/lw/anaconda3/envs/autolabel/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/lw/anaconda3/envs/autolabel/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/lw/anaconda3/envs/autolabel/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lw/anaconda3/envs/autolabel/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lw/autolabel-main/data/dataset.py", line 207, in __getitem__
    return self.get(video, label, segment_indices, video_id)
  File "/home/lw/autolabel-main/data/dataset.py", line 229, in get
    seg_imgs = [Image.open(frame_paths[p]).convert("RGB")]
IndexError: list index out of range_
```
How should I solve this problem？

**Comment by liwell24** [comment]
I have solved the problem . Thank you ! :)

**Comment by Better-byte** [comment]
How did you solve it? I also encountered this problem.
